### PR TITLE
Add naggin feature

### PR DESCRIPTION
**Pull request by jonasbleyl**

### CODE REVIEW

**Comment by Llamatron2112** [comment]
This is indeed cleaner and simpler than my version, and it's not a problem to have the nag set globally..

The only things that I think is missing are another way to snooze than using the notification action, and a way to dismiss the alert when there's no notification (during a snooze for example).

The UI I added is just the default view activity with dismiss and snooze buttons added if the alarm is running or on snooze, and I couldn't think of a simpler way than adding this active state boolean. This way users can even open the app and navigate to the reminder they want to manage, or for people who open the notification from the lock screen, so they land directly on a page where they can manage the alarm.

**Comment by jonasbleyl** [comment]
Yeah the only real way of doing this is by having an active state boolean like you added previously. The problem with this is that it adds this intermediate state for the reminder like I talked about earlier. This is something I wanted to avoid as I know it'll cause issues down the road.

It also makes it a bit more complex. For example, the user enters the app and goes onto the current ongoing reminder. This would show the user the new UI with the option to snooze, mark as done, etc. If the user decides to snooze from the button on the notification instead, then the current UI of the reminder has to be updated. It adds quite bit more logic to just the snooze option. This will be the same for any other actions, including those that might be added in the future.

A way to cancel the reminder's snooze is probably a good idea. Though yeah to tell if it has been snoozed one would need the active state again. I guess we can add an option to cancel any snoozed alarms to all reminders as cancelling an alarm with an ID that doesn't exist doesn't cause any problems. It's not the prettiest solution though.

**Comment by Llamatron2112** [comment]
I was just thinking it would be a good idea to have a way to know a reminder's status, even for further features, and apparently making the UI react to changes is quite easy with local broadcasts, at least I did one for the example you mentionned and it was quite easy, not sure of the right way to dynamically create, pause or close receivers tho I'd have to do some experiments (commit is here https://github.com/Llamatron2112/Recurrence/commit/8571d13903f75347c9417903e89705839c521d37 ).

Also the way you did the notification "life cycle" seems pretty similar to mine, is it really just the active state thing that makes it an intermediate state ?

But I understand you wanting things to stay as clean simple as possible too.

**Comment by jonasbleyl** [comment]
Hi, sorry for the late reply!

Yeah you're completely right about the local broadcast receiver. It's already being used in the TabFragment and works perfectly.

From what I've read however the correct way to use it is to register it in the onResume and then to unregister it in the onPause. This is because onDestroy is never guaranteed to be called. Continuing to update our activity while it isn't visible would be considered bad practice anyway.

I've decided not to add the active state to the reminders for now. If I were to add it then I would want to change the ordering of the reminders in the list so that the active ones are at the top and not set to their new alarms. I'll have a think about whether or not I still want to change this later on.

I think I'll merge this as I have a bit of time and want to work on other parts of the app.

Thanks for your help! Would you mind if I added you to the "Thanks to" section to the app as a contributor? Let me know if you'd like your name or some alias there :)

**Pull request merged**
