### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by greizgh**
I did not see new strings? Maybe I'm missing something?

### CODE REVIEW

**Comment by jonasbleyl** [comment]
It seems that you haven't updated your fork with the new commits on the dev branch. That's why you're not seeing the new strings.

**Comment by greizgh** [comment]
My bad, should be OK now.

**Comment by jonasbleyl** [comment]
Looking good. Though there's two strings missing in the repeat_array however. "Every hour" and "Advanced".

**Comment by greizgh** [comment]
Fixed!

**Comment by jonasbleyl** [comment]
Thanks! Would you like your name or an alias added to the about section of the app as a translator?

**Comment by greizgh** [comment]
Thank you, you can credit me as greizgh.

**Comment by jonasbleyl** [comment]
Will do, thanks again.

**Pull request merged**
